apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    cert-manager.io/issuer: "letsencrypt-prod"
  name: cryptozoon-public
spec:
  tls:
    - hosts:
        - "cryptozoon.{{ .Values.ingress.hostname }}"
      secretName: cryptozoon-public-tls
  rules:
    - host: "cryptozoon.{{ .Values.ingress.hostname }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cryptozoon
                port:
                  number: 3001
